pluginName = XMI Exporter
providerName = Proyecto Astah
bundle.name = XMI Exporter
bundle.description = Exportador XMI para Astah con modo nativo y base para exportadores propios.

action_set_label=XMI Exporter
menu_group=XMI Exporter
export_xmi_menu_label=&Export XMI...
export_xmi_menu_tooltip=Exportar el proyecto abierto a XMI
